# Generated by Django 5.0.1 on 2024-04-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
