# Generated by Django 5.0.1 on 2024-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='A1star', max_length=100),
        ),
    ]
